; This file was auto-generated by drush_make
core = 6.x

api = 2

includes[ldp] = "https://github.com/johngriffin/ldp-kit/raw/master/ldp.make"


projects[rubik][version] = "3.0-beta2"
projects[rubik][type] = "theme"

projects[tao][version] = "3.2"
projects[tao][type] = "theme"

projects[jake][location] = http://code.developmentseed.org/fserver
projects[jake][version] = 1.0-beta15

projects[menu_block][subdir] = "contrib"
projects[menu_block][version] = "2.4"
