<?php

/**
 * Implementation of hook_ctools_plugin_api().
 */
function ds_topics_ctools_plugin_api() {
  list($module, $api) = func_get_args();
  if ($module == "context" && $api == "context") {
    return array("version" => 3);
  }
  elseif ($module == "feeds" && $api == "feeds_importer_default") {
    return array("version" => 1);
  }
  elseif ($module == "page_manager" && $api == "pages_default") {
    return array("version" => 1);
  }
}

/**
 * Implementation of hook_views_api().
 */
function ds_topics_views_api() {
  return array(
    'api' => '3.0-alpha1',
  );
}
