<?php

/**
 * Implementation of hook_menu().
 */
function ds_motion_chart_menu() {
  return array(
    'motion_chart' => array(
      'title' => 'Motion Chart',
      'description' => '',
      'access arguments' => array('access content'),
      'page callback' => 'ds_motion_chart_page',
    ),
  );
}

function ds_motion_chart_page() {
  
  drupal_set_html_head('<script type="text/javascript" src="https://www.google.com/jsapi"></script>');
  drupal_add_js(drupal_get_path('module', 'ds_motion_chart') . '/js/indicators.js');
  drupal_add_js("$(document).ready( function() {changeData();} );", 'inline');
  
  return '<div id="visualization"></div>';
}